CREATE DATABASE USER_NEWS_FEED;
USE USER_NEWS_FEED;
CREATE TABLE userprofile (user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,firstname VARCHAR(20) NOT NULL,lastname VARCHAR(20) NOT NULL, nickname VARCHAR(20) NOT NULL, encrp_password VARCHAR(100) NOT NULL, email VARCHAR(50) NOT NULL, birth DATE, gender CHAR(1) NOT NULL, status VARCHAR(100), salt VARCHAR(50) NOT NULL);